version: '3.4'

services:
  taskmanagementservice:
    image: ${DOCKER_REGISTRY-}taskmanagementservice
    build:
      context: .
      dockerfile: TaskManagementService/Dockerfile
    environment:
      - Services__Identity__BaseAddress=http://identity
      - ConnectionStrings__Mongo=mongodb://root:Xq5xrtzEKj44ueyd@mongo:27017/HabiticaTaskProviderService?authSource=admin
      - ConnectionStrings__RabbitMQ=amqp://rabbit:EvtNt7PKZqNNT06T@rabbitmq
      - ApiResource__ApiName=task-api
      - ApiResource__ApiSecret=B01SeaEDdDBGDLeqUCHuPSUhuSXsa8VEsvvEp6bfb804hLcVZ1bcJkZDB/crtsSG2xzzgiRxjZuHDsalPs2JZg==
      - Account__ClientId=UserManagementClient
      - Account__ClientSecret=G4QJrKZSRQ4PO6yDX/WxY7OxZbGol7hPO7u/hv1kt1cRwn34+wOHJ26jL+kBRk9mmSIXn98HMoTLunHrkr4Qqw==
    networks:
      - lionize

networks:
      lionize:
        external:
          name: lionize